const INCREMENT = "INCREMENT_COUNTER"
const DECREMENT = "DECREMENT_COUNTER"
const RESET = "RESET_COUNTER"
const ADD_COUNTER = "ADD_COUNTER"

export {
    INCREMENT,
    DECREMENT,
    RESET,
    ADD_COUNTER
}