const FETCH_TASK_REQUEST = 'FETCH_TASK_REQUEST'
const FETCH_TASK_SUCCESS = 'FETCH_TASK_SUCCESS'
const FETCH_TASK_FAILURE = 'FETCH_TASK_FAILURE'
const ADD_TASK_REQUEST = 'ADD_TASK_REQUEST'
const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS'
const ADD_TASK_FAILURE = 'ADD_TASK_FAILURE'
const DELETE_TASK_REQUEST = 'DELETE_TASK_REQUEST'
const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS'
const DELETE_TASK_FAILURE = 'DELETE_TASK_FAILURE'

export {
    FETCH_TASK_REQUEST,
    FETCH_TASK_SUCCESS,
    FETCH_TASK_FAILURE,
    ADD_TASK_REQUEST,
    ADD_TASK_SUCCESS,
    ADD_TASK_FAILURE,
    DELETE_TASK_REQUEST,
    DELETE_TASK_SUCCESS,
    DELETE_TASK_FAILURE
}